---
- hosts: defaults
  become: true
  tasks:
  - name: install apache
    apt: name=apache2 update_cache=yes state=latest
  - name: Clone Git repository
    git:
      repo: https://github.com/JulesRe/cat_web
      dest: /var/www/html/cat_web
      clone: yes
      update: yes 
  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
    - name: Restart Apache
      service:
        name: apache2